name: notelytask
description: A simple notes application.

publish_to: "none"

version: 4.0.0

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.5
  hydrated_bloc: ^9.1.5
  path_provider: ^2.1.2
  json_serializable: ^6.7.1
  build_runner: ^2.4.8
  http: ^1.2.1
  get_storage: ^2.1.1
  url_launcher: ^6.2.5
  equatable: ^2.0.5
  home_widget: ^0.7.0
  crypto: ^3.0.3
  get_it: ^8.0.3

  flutter_web_plugins:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_annotation: ^4.0.1
  file_picker: ^8.1.6
  collection: ^1.18.0
  open_filex: ^4.7.0
  share_plus: ^10.1.3
  keyboard_detection: ^0.8.1
  encrypt: ^5.0.3
  pinput: ^5.0.0
  flutter_code_editor: ^0.3.2
  highlight: ^0.7.0
  flutter_widget_from_html: ^0.15.3
  http_parser: ^4.0.2
  flutter_secure_storage: ^9.2.2
  package_info_plus: ^8.3.0
  flutter_highlight: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.2

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
    - assets/foreground.png
    - assets/github.png

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_foreground: "assets/foreground.png"
  adaptive_icon_background: "#ffffff"
