name: notelytask
description: A new Flutter project.

publish_to: 'none'

version: 2.0.5+65

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: 7.3.3
  hydrated_bloc: 7.1.0
  path_provider: 2.0.1
  json_serializable: 4.1.0
  build_runner: 1.12.2
  http: 0.13.4
  get_storage: 2.0.1
  url_launcher: 6.0.12
  equatable: 2.0.3
  flutter_dotenv: 5.0.2

  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: 0.9.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
    - assets/foreground.png
    - assets/github.png
    - assets/.env

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_foreground: "assets/foreground.png"
  adaptive_icon_background: "#ffffff"