name: notelytask
description: A simple notes application.

publish_to: 'none'

version: 3.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.5
  hydrated_bloc: ^9.1.5
  path_provider: ^2.1.2
  json_serializable: ^6.7.1
  build_runner: ^2.4.8
  http: ^1.2.1
  get_storage: ^2.1.1
  url_launcher: ^6.2.5
  equatable: ^2.0.5
  flutter_dotenv: ^5.1.0
  home_widget: ^0.4.1
  get_it: ^7.6.7

  flutter_web_plugins:
    sdk: flutter
  flutter_lints: ^3.0.1
  json_annotation: ^4.0.1
  file_picker: ^6.2.0
  collection: ^1.18.0
  open_filex: ^4.4.0
  share_plus: ^7.2.2
  flutter_keyboard_visibility: ^6.0.0
  encrypt: ^5.0.3
  pinput: ^4.0.0
  flutter_markdown: ^0.6.22
  flutter_widget_from_html: ^0.14.11
  google_sign_in: ^6.2.1
  http_parser: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
    - assets/foreground.png
    - assets/github.png
    - assets/.env

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_foreground: "assets/foreground.png"
  adaptive_icon_background: "#ffffff"